### ISSUE TITLE
Using `--PileupFile` results in wildly incorrect contamination estimate

### ISSUE THREAD

**Issue by jrandall** [Griffan/VerifyBamID#8]
This is what happens if you generate an `--OutputPileup` using VerifyBamID and then process that output using `--PileupFile` (on a rather contaminated sample):
```
$ VerifyBamID --BamFile 17995_6#10.bam --UDPath /resource/hgdp.10k.b38.vcf.gz.dat.UD --BedPath /resource/hgdp.10k.b38.vcf.gz.dat.bed --MeanPath /resource/hgdp.10k.b38.vcf.gz.dat.mu --Reference /data/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa --Output 17995_6#10.vbid2.hgdp.10k.out --OutputPileup
$ cat 17995_6#10.vbid2.hgdp.10k.out.selfSM
#SEQ_ID RG      CHIP_ID #SNPS   #READS  AVG_DP  FREEMIX FREELK1 FREELK0 FREE_RH FREE_RA CHIPMIX CHIPLK1 CHIPLK0 CHIP_RH CHIP_RA DPREF   RDPHET   RDPALT
EGAN00001217480 NA      NA      9997    29278   2.92868 0.0802537       -13398.2        -13499.5        NA      NA      NA      NA      NA       NA      NA      NA      NA      NA
$ VerifyBamID --PileupFile 17995_6#10.vbid2.hgdp.10k.out.Pileup --UDPath /resource/hgdp.10k.b38.vcf.gz.dat.UD --BedPath /resource/hgdp.10k.b38.vcf.gz.dat.bed --MeanPath /resource/hgdp.10k.b38.vcf.gz.dat.mu --Reference /data/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa --Output 17995_6#10.vbid2.hgdp.10k.from-vbid2-pileup.out
$ cat 17995_6#10.vbid2.hgdp.10k.pileup.out.selfSM
#SEQ_ID RG      CHIP_ID #SNPS   #READS  AVG_DP  FREEMIX FREELK1 FREELK0 FREE_RH FREE_RA CHIPMIX CHIPLK1 CHIPLK0 CHIP_RH CHIP_RA DPREF   RDPHET   RDPALT
        NA      NA      9997    1803135200      4.59121e-41     2.60408e-07     -180050 -196712 NA      NA      NA      NA      NA      NA       NA      NA      NA      NA
```

I've shown this example for the sake of reproducibility, but I find the same problem when generating a pileup with samtools. Is contamination estimation broken when using `--PileupFile`?

**Comment by Griffan** [comment]
Thanks, @jrandall 
This problem was caused by a redundant "." / "," translation, and now this has been fixed according to my test run. 
If you still found any errors, please let us know.

**Comment by jrandall** [comment]
Thanks to the quick attention! It looks like things are somewhat better now, but with the new version (1.0.3) I am still not seeing identical results from `--BamFile` and from `--PileupFile` generated from the BAM file. 
```
$ VerifyBamID --BamFile 17995_6#10.bam --UDPath /resource/hgdp.10k.b38.vcf.gz.dat.UD --BedPath /resource/hgdp.10k.b38.vcf.gz.dat.bed --MeanPath /resource/hgdp.10k.b38.vcf.gz.da
t.mu --Reference /data/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa --Output 17995_6#10.verifybamid-1.0.3.hgdp.10k.frombam.out --OutputPileup
...
NOTICE - Mean Depth:3.096235
NOTICE - SD Depth:1.567787
NOTICE - Filtered 92 low-quality SNP markers.
NOTICE - Passing Marker Sanity Check...
Estimation from OptimizeHeter:
Contaminating Sample PC1:0.00574189     PC2:-0.0224274
Intended Sample PC1:0.017017    PC2:-0.03053
Alpha:0.0434112
$ cat 17995_6#10.verifybamid-1.0.3.hgdp.10k.frombam.out.selfSM
#SEQ_ID RG      CHIP_ID #SNPS   #READS  AVG_DP  FREEMIX FREELK1 FREELK0 FREE_RH FREE_RA CHIPMIX CHIPLK1 CHIPLK0 CHIP_RH CHIP_RA DPREF   RDPHET  RDPALT
EGAN00001217480 NA      NA      9997    3       3.09624 0.0434112       -13632.6        -13714.8        NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
$ VerifyBamID --PileupFile 17995_6#10.verifybamid-1.0.3.hgdp.10k.frombam.out.Pileup --UDPath /resource/hgdp.10k.b38.vcf.gz.dat.UD --BedPath /resource/hgdp.10k.b38.vcf.gz.dat.bed --MeanPath /resource/hgdp.10k.b38.vcf.gz.dat.mu --Reference /data/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa --Output 17995_6#10.verifybamid-1.0.3.hgdp.10k.from-vbid-pileup.out
...
NOTICE - Passing Marker Sanity Check...
Estimation from OptimizeHeter:
Contaminating Sample PC1:0.0131898      PC2:-0.0322141
Intended Sample PC1:0.0171688   PC2:-0.0309399
Alpha:0.0796773
$ cat 17995_6#10.verifybamid-1.0.3.hgdp.10k.from-vbid-pileup.out.selfSM
#SEQ_ID RG      CHIP_ID #SNPS   #READS  AVG_DP  FREEMIX FREELK1 FREELK0 FREE_RH FREE_RA CHIPMIX CHIPLK1 CHIPLK0 CHIP_RH CHIP_RA DPREF   RDPHET  RDPALT
        NA      NA      9997    3       3.07826 0.0796773       -13485.9        -13586.8        NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
```

Version 1.0.2 calculates a freemix of 0.0802537 from BAM input and 2.60408e-07 from the associated Pileup input. Version 1.0.3 calculates a freemix of 0.0434112 from the same BAM file, and 0.0796773 from the associated Pileup input. So it seems that the prior version BAM input and the current version Pileup input nearly agree, but the new version BAM input is off by almost a factor of 2 in the contamination estimate. 

Something also appears to be off with the `#READS` output in 1.0.3 (it reports exactly 3 reads for both BAM and Pileup inputs).

**Comment by Griffan** [comment]
First of all, since 1.0.3, we added marker sanity check before running estimation. if your sample has spurious copy number(or high variance of depth) at some regions(e.g. non-diploid or tumor sample), this will remove some of the markers in use. If not, please let me know. 

You can use --DisableSanityCheck to avoid use this feature also.

As for the number of reads, because we only select reads from target region(predefined markers), we don't have a precise number of reads in original bam file(especially for pileup), so here is an read number estimation, and yes, this is also a bug in last push. 

We have updated the commit according to your report. You can give it a try again.

Thanks for  your help!

**Comment by jrandall** [comment]
The commit currently tagged 1.0.3 is from before the fix: https://github.com/Griffan/VerifyBamID/tree/1.0.3 

Perhaps you could delete the 1.0.3 tag and re-tag it as 6c7894cb ?

**Comment by Griffan** [comment]
I see, thank you very much!
